services:
  - type: web
    name: loan-analysis-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODEL_PATH
        value: loan_default_model_v2.pkl
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FRONTEND_URL
        value: https://loan-analysis-system-4xw7gncli-bigtime5s-projects.vercel.app
      - key: ADMIN_USER
        value: ceo
      - key: ADMIN_PASS
        value: securepassword
    healthCheckPath: /health
